#!/usr/bin/env bash
# aws-local-lab :: aws-local-env.sh
#
# Emit a ready-to-source env file (and optionally a docker-compose override
# snippet) that wires any project at the local AWS lab in one command.
#
#   Host shell, into your project:
#     ./integration/aws-local-env.sh > .aws-local.env && source .aws-local.env
#
#   Compose override for a containerised project:
#     ./integration/aws-local-env.sh --compose > docker-compose.override.yml
#
#   Force the hostname when auto-detection cannot decide:
#     ./integration/aws-local-env.sh --host        # localhost:4566  (default off-network)
#     ./integration/aws-local-env.sh --network     # aws-local-lab:4566 (inside the shared net)
#
# Detection: if this process can resolve the Docker service name
# "aws-local-lab", we are on the shared network and use the in-network
# endpoint; otherwise we use the published host port.
set -eu

NETWORK_NAME="aws-local-lab"
IN_NETWORK_HOST="aws-local-lab"
HOST_HOST="localhost"
EDGE_PORT="${EDGE_PORT:-4566}"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"

mode="auto"
emit="env"
for arg in "$@"; do
  case "$arg" in
    --host)     mode="host" ;;
    --network)  mode="network" ;;
    --compose)  emit="compose" ;;
    --env)      emit="env" ;;
    -h|--help)  sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [ "$mode" = "auto" ]; then
  if getent hosts "$IN_NETWORK_HOST" >/dev/null 2>&1 || \
     python3 -c "import socket,sys; socket.gethostbyname('$IN_NETWORK_HOST')" >/dev/null 2>&1; then
    mode="network"
  else
    mode="host"
  fi
fi

if [ "$mode" = "network" ]; then
  endpoint="http://${IN_NETWORK_HOST}:4566"
else
  endpoint="http://${HOST_HOST}:${EDGE_PORT}"
fi

if [ "$emit" = "compose" ]; then
  cat <<YAML
# Generated by integration/aws-local-env.sh - drop next to your docker-compose.yml.
# Joins the shared lab network and points the AWS SDK/CLI at LocalStack.
networks:
  ${NETWORK_NAME}:
    external: true

services:
  app:
    networks:
      - ${NETWORK_NAME}
    environment:
      AWS_ENDPOINT_URL: "http://${IN_NETWORK_HOST}:4566"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_DEFAULT_REGION: "${REGION}"
      AWS_REGION: "${REGION}"
YAML
  exit 0
fi

cat <<ENV
# Generated by integration/aws-local-env.sh (mode: ${mode})
# Source this file:  source .aws-local.env
export AWS_ENDPOINT_URL="${endpoint}"
export AWS_ENDPOINT_URL_S3="${endpoint}"
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export AWS_DEFAULT_REGION="${REGION}"
export AWS_REGION="${REGION}"
ENV
